// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: originData.proto

package com.autoai.wedata.kittx.uds.log.bean.pbv26;

public final class OriginDataBean {
  private OriginDataBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OriginDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *	数据ID
     * </pre>
     *
     * <code>string data_id = 1;</code>
     */
    java.lang.String getDataId();
    /**
     * <pre>
     *	数据ID
     * </pre>
     *
     * <code>string data_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataIdBytes();

    /**
     * <pre>
     *env的数值
     * </pre>
     *
     * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
     */
    boolean hasEnv();
    /**
     * <pre>
     *env的数值
     * </pre>
     *
     * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env getEnv();
    /**
     * <pre>
     *env的数值
     * </pre>
     *
     * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.EnvOrBuilder getEnvOrBuilder();

    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track> 
        getTrackList();
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track getTrack(int index);
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    int getTrackCount();
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder> 
        getTrackOrBuilderList();
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder getTrackOrBuilder(
        int index);

    /**
     * <pre>
     * </pre>
     *
     * <code>string ext = 4;</code>
     */
    java.lang.String getExt();
    /**
     * <pre>
     * </pre>
     *
     * <code>string ext = 4;</code>
     */
    com.google.protobuf.ByteString
        getExtBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>string gen_ts = 5;</code>
     */
    java.lang.String getGenTs();
    /**
     * <pre>
     * </pre>
     *
     * <code>string gen_ts = 5;</code>
     */
    com.google.protobuf.ByteString
        getGenTsBytes();

    /**
     * <pre>
     *车机数据包状态
     * </pre>
     *
     * <code>string status = 6;</code>
     */
    java.lang.String getStatus();
    /**
     * <pre>
     *车机数据包状态
     * </pre>
     *
     * <code>string status = 6;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginData}
   */
  public  static final class OriginData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginData)
      OriginDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OriginData.newBuilder() to construct.
    private OriginData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OriginData() {
      dataId_ = "";
      track_ = java.util.Collections.emptyList();
      ext_ = "";
      genTs_ = "";
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OriginData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dataId_ = s;
              break;
            }
            case 18: {
              com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.Builder subBuilder = null;
              if (env_ != null) {
                subBuilder = env_.toBuilder();
              }
              env_ = input.readMessage(com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(env_);
                env_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                track_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track>();
                mutable_bitField0_ |= 0x00000004;
              }
              track_.add(
                  input.readMessage(com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.parser(), extensionRegistry));
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ext_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              genTs_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          track_ = java.util.Collections.unmodifiableList(track_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData.class, com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData.Builder.class);
    }

    private int bitField0_;
    public static final int DATA_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataId_;
    /**
     * <pre>
     *	数据ID
     * </pre>
     *
     * <code>string data_id = 1;</code>
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *	数据ID
     * </pre>
     *
     * <code>string data_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENV_FIELD_NUMBER = 2;
    private com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env env_;
    /**
     * <pre>
     *env的数值
     * </pre>
     *
     * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
     */
    public boolean hasEnv() {
      return env_ != null;
    }
    /**
     * <pre>
     *env的数值
     * </pre>
     *
     * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env getEnv() {
      return env_ == null ? com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.getDefaultInstance() : env_;
    }
    /**
     * <pre>
     *env的数值
     * </pre>
     *
     * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.EnvOrBuilder getEnvOrBuilder() {
      return getEnv();
    }

    public static final int TRACK_FIELD_NUMBER = 3;
    private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track> track_;
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track> getTrackList() {
      return track_;
    }
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder> 
        getTrackOrBuilderList() {
      return track_;
    }
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    public int getTrackCount() {
      return track_.size();
    }
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track getTrack(int index) {
      return track_.get(index);
    }
    /**
     * <pre>
     *track的数值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder getTrackOrBuilder(
        int index) {
      return track_.get(index);
    }

    public static final int EXT_FIELD_NUMBER = 4;
    private volatile java.lang.Object ext_;
    /**
     * <pre>
     * </pre>
     *
     * <code>string ext = 4;</code>
     */
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string ext = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GEN_TS_FIELD_NUMBER = 5;
    private volatile java.lang.Object genTs_;
    /**
     * <pre>
     * </pre>
     *
     * <code>string gen_ts = 5;</code>
     */
    public java.lang.String getGenTs() {
      java.lang.Object ref = genTs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genTs_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string gen_ts = 5;</code>
     */
    public com.google.protobuf.ByteString
        getGenTsBytes() {
      java.lang.Object ref = genTs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genTs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private volatile java.lang.Object status_;
    /**
     * <pre>
     *车机数据包状态
     * </pre>
     *
     * <code>string status = 6;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *车机数据包状态
     * </pre>
     *
     * <code>string status = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataId_);
      }
      if (env_ != null) {
        output.writeMessage(2, getEnv());
      }
      for (int i = 0; i < track_.size(); i++) {
        output.writeMessage(3, track_.get(i));
      }
      if (!getExtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ext_);
      }
      if (!getGenTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, genTs_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataId_);
      }
      if (env_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEnv());
      }
      for (int i = 0; i < track_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, track_.get(i));
      }
      if (!getExtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ext_);
      }
      if (!getGenTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, genTs_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData)) {
        return super.equals(obj);
      }
      com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData other = (com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData) obj;

      if (!getDataId()
          .equals(other.getDataId())) return false;
      if (hasEnv() != other.hasEnv()) return false;
      if (hasEnv()) {
        if (!getEnv()
            .equals(other.getEnv())) return false;
      }
      if (!getTrackList()
          .equals(other.getTrackList())) return false;
      if (!getExt()
          .equals(other.getExt())) return false;
      if (!getGenTs()
          .equals(other.getGenTs())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDataId().hashCode();
      if (hasEnv()) {
        hash = (37 * hash) + ENV_FIELD_NUMBER;
        hash = (53 * hash) + getEnv().hashCode();
      }
      if (getTrackCount() > 0) {
        hash = (37 * hash) + TRACK_FIELD_NUMBER;
        hash = (53 * hash) + getTrackList().hashCode();
      }
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + getExt().hashCode();
      hash = (37 * hash) + GEN_TS_FIELD_NUMBER;
      hash = (53 * hash) + getGenTs().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginData)
        com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData.class, com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData.Builder.class);
      }

      // Construct using com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTrackFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataId_ = "";

        if (envBuilder_ == null) {
          env_ = null;
        } else {
          env_ = null;
          envBuilder_ = null;
        }
        if (trackBuilder_ == null) {
          track_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          trackBuilder_.clear();
        }
        ext_ = "";

        genTs_ = "";

        status_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_descriptor;
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData getDefaultInstanceForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData.getDefaultInstance();
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData build() {
        com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData buildPartial() {
        com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData result = new com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.dataId_ = dataId_;
        if (envBuilder_ == null) {
          result.env_ = env_;
        } else {
          result.env_ = envBuilder_.build();
        }
        if (trackBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            track_ = java.util.Collections.unmodifiableList(track_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.track_ = track_;
        } else {
          result.track_ = trackBuilder_.build();
        }
        result.ext_ = ext_;
        result.genTs_ = genTs_;
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData) {
          return mergeFrom((com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData other) {
        if (other == com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData.getDefaultInstance()) return this;
        if (!other.getDataId().isEmpty()) {
          dataId_ = other.dataId_;
          onChanged();
        }
        if (other.hasEnv()) {
          mergeEnv(other.getEnv());
        }
        if (trackBuilder_ == null) {
          if (!other.track_.isEmpty()) {
            if (track_.isEmpty()) {
              track_ = other.track_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTrackIsMutable();
              track_.addAll(other.track_);
            }
            onChanged();
          }
        } else {
          if (!other.track_.isEmpty()) {
            if (trackBuilder_.isEmpty()) {
              trackBuilder_.dispose();
              trackBuilder_ = null;
              track_ = other.track_;
              bitField0_ = (bitField0_ & ~0x00000004);
              trackBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTrackFieldBuilder() : null;
            } else {
              trackBuilder_.addAllMessages(other.track_);
            }
          }
        }
        if (!other.getExt().isEmpty()) {
          ext_ = other.ext_;
          onChanged();
        }
        if (!other.getGenTs().isEmpty()) {
          genTs_ = other.genTs_;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object dataId_ = "";
      /**
       * <pre>
       *	数据ID
       * </pre>
       *
       * <code>string data_id = 1;</code>
       */
      public java.lang.String getDataId() {
        java.lang.Object ref = dataId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *	数据ID
       * </pre>
       *
       * <code>string data_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataIdBytes() {
        java.lang.Object ref = dataId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *	数据ID
       * </pre>
       *
       * <code>string data_id = 1;</code>
       */
      public Builder setDataId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	数据ID
       * </pre>
       *
       * <code>string data_id = 1;</code>
       */
      public Builder clearDataId() {
        
        dataId_ = getDefaultInstance().getDataId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	数据ID
       * </pre>
       *
       * <code>string data_id = 1;</code>
       */
      public Builder setDataIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataId_ = value;
        onChanged();
        return this;
      }

      private com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env env_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env, com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.EnvOrBuilder> envBuilder_;
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public boolean hasEnv() {
        return envBuilder_ != null || env_ != null;
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env getEnv() {
        if (envBuilder_ == null) {
          return env_ == null ? com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.getDefaultInstance() : env_;
        } else {
          return envBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public Builder setEnv(com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env value) {
        if (envBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          env_ = value;
          onChanged();
        } else {
          envBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public Builder setEnv(
          com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.Builder builderForValue) {
        if (envBuilder_ == null) {
          env_ = builderForValue.build();
          onChanged();
        } else {
          envBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public Builder mergeEnv(com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env value) {
        if (envBuilder_ == null) {
          if (env_ != null) {
            env_ =
              com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.newBuilder(env_).mergeFrom(value).buildPartial();
          } else {
            env_ = value;
          }
          onChanged();
        } else {
          envBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public Builder clearEnv() {
        if (envBuilder_ == null) {
          env_ = null;
          onChanged();
        } else {
          env_ = null;
          envBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.Builder getEnvBuilder() {
        
        onChanged();
        return getEnvFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.EnvOrBuilder getEnvOrBuilder() {
        if (envBuilder_ != null) {
          return envBuilder_.getMessageOrBuilder();
        } else {
          return env_ == null ?
              com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.getDefaultInstance() : env_;
        }
      }
      /**
       * <pre>
       *env的数值
       * </pre>
       *
       * <code>.com.autoai.wedata.kittx.uds.log.bean.pbv26.Env env = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env, com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.EnvOrBuilder> 
          getEnvFieldBuilder() {
        if (envBuilder_ == null) {
          envBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env, com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.Env.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.EnvOrBuilder>(
                  getEnv(),
                  getParentForChildren(),
                  isClean());
          env_ = null;
        }
        return envBuilder_;
      }

      private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track> track_ =
        java.util.Collections.emptyList();
      private void ensureTrackIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          track_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track>(track_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder> trackBuilder_;

      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track> getTrackList() {
        if (trackBuilder_ == null) {
          return java.util.Collections.unmodifiableList(track_);
        } else {
          return trackBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public int getTrackCount() {
        if (trackBuilder_ == null) {
          return track_.size();
        } else {
          return trackBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track getTrack(int index) {
        if (trackBuilder_ == null) {
          return track_.get(index);
        } else {
          return trackBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder setTrack(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track value) {
        if (trackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrackIsMutable();
          track_.set(index, value);
          onChanged();
        } else {
          trackBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder setTrack(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder builderForValue) {
        if (trackBuilder_ == null) {
          ensureTrackIsMutable();
          track_.set(index, builderForValue.build());
          onChanged();
        } else {
          trackBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder addTrack(com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track value) {
        if (trackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrackIsMutable();
          track_.add(value);
          onChanged();
        } else {
          trackBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder addTrack(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track value) {
        if (trackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrackIsMutable();
          track_.add(index, value);
          onChanged();
        } else {
          trackBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder addTrack(
          com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder builderForValue) {
        if (trackBuilder_ == null) {
          ensureTrackIsMutable();
          track_.add(builderForValue.build());
          onChanged();
        } else {
          trackBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder addTrack(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder builderForValue) {
        if (trackBuilder_ == null) {
          ensureTrackIsMutable();
          track_.add(index, builderForValue.build());
          onChanged();
        } else {
          trackBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder addAllTrack(
          java.lang.Iterable<? extends com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track> values) {
        if (trackBuilder_ == null) {
          ensureTrackIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, track_);
          onChanged();
        } else {
          trackBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder clearTrack() {
        if (trackBuilder_ == null) {
          track_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          trackBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public Builder removeTrack(int index) {
        if (trackBuilder_ == null) {
          ensureTrackIsMutable();
          track_.remove(index);
          onChanged();
        } else {
          trackBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder getTrackBuilder(
          int index) {
        return getTrackFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder getTrackOrBuilder(
          int index) {
        if (trackBuilder_ == null) {
          return track_.get(index);  } else {
          return trackBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder> 
           getTrackOrBuilderList() {
        if (trackBuilder_ != null) {
          return trackBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(track_);
        }
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder addTrackBuilder() {
        return getTrackFieldBuilder().addBuilder(
            com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.getDefaultInstance());
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder addTrackBuilder(
          int index) {
        return getTrackFieldBuilder().addBuilder(
            index, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.getDefaultInstance());
      }
      /**
       * <pre>
       *track的数值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv26.Track track = 3;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder> 
           getTrackBuilderList() {
        return getTrackFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder> 
          getTrackFieldBuilder() {
        if (trackBuilder_ == null) {
          trackBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.Track.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.TrackOrBuilder>(
                  track_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          track_ = null;
        }
        return trackBuilder_;
      }

      private java.lang.Object ext_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string ext = 4;</code>
       */
      public java.lang.String getExt() {
        java.lang.Object ref = ext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string ext = 4;</code>
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        java.lang.Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string ext = 4;</code>
       */
      public Builder setExt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ext_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string ext = 4;</code>
       */
      public Builder clearExt() {
        
        ext_ = getDefaultInstance().getExt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string ext = 4;</code>
       */
      public Builder setExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ext_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object genTs_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string gen_ts = 5;</code>
       */
      public java.lang.String getGenTs() {
        java.lang.Object ref = genTs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          genTs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string gen_ts = 5;</code>
       */
      public com.google.protobuf.ByteString
          getGenTsBytes() {
        java.lang.Object ref = genTs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string gen_ts = 5;</code>
       */
      public Builder setGenTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        genTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string gen_ts = 5;</code>
       */
      public Builder clearGenTs() {
        
        genTs_ = getDefaultInstance().getGenTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string gen_ts = 5;</code>
       */
      public Builder setGenTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        genTs_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <pre>
       *车机数据包状态
       * </pre>
       *
       * <code>string status = 6;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *车机数据包状态
       * </pre>
       *
       * <code>string status = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *车机数据包状态
       * </pre>
       *
       * <code>string status = 6;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车机数据包状态
       * </pre>
       *
       * <code>string status = 6;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车机数据包状态
       * </pre>
       *
       * <code>string status = 6;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginData)
    }

    // @@protoc_insertion_point(class_scope:com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginData)
    private static final com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData();
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OriginData>
        PARSER = new com.google.protobuf.AbstractParser<OriginData>() {
      @java.lang.Override
      public OriginData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OriginData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OriginData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OriginData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.autoai.wedata.kittx.uds.log.bean.pbv26.OriginDataBean.OriginData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020originData.proto\022*com.autoai.wedata.ki" +
      "ttx.uds.log.bean.pbv26\032\tenv.proto\032\013track" +
      ".proto\"\312\001\n\nOriginData\022\017\n\007data_id\030\001 \001(\t\022<" +
      "\n\003env\030\002 \001(\0132/.com.autoai.wedata.kittx.ud" +
      "s.log.bean.pbv26.Env\022@\n\005track\030\003 \003(\01321.co" +
      "m.autoai.wedata.kittx.uds.log.bean.pbv26" +
      ".Track\022\013\n\003ext\030\004 \001(\t\022\016\n\006gen_ts\030\005 \001(\t\022\016\n\006s" +
      "tatus\030\006 \001(\tB\020B\016OriginDataBeanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.getDescriptor(),
          com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.getDescriptor(),
        }, assigner);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv26_OriginData_descriptor,
        new java.lang.String[] { "DataId", "Env", "Track", "Ext", "GenTs", "Status", });
    com.autoai.wedata.kittx.uds.log.bean.pbv26.EnvBean.getDescriptor();
    com.autoai.wedata.kittx.uds.log.bean.pbv26.TrackBean.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
