// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: err.proto

package com.autoai.wedata.kittx.uds.log.bean.pbv2;

public final class ErrBean {
  private ErrBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autoai.wedata.kittx.uds.log.bean.pbv2.Err)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 终端唯一识别号
     * </pre>
     *
     * <code>string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     * 终端唯一识别号
     * </pre>
     *
     * <code>string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     * 应用（产品）唯一标识
     * </pre>
     *
     * <code>string app_id = 2;</code>
     */
    java.lang.String getAppId();
    /**
     * <pre>
     * 应用（产品）唯一标识
     * </pre>
     *
     * <code>string app_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string session_id = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string session_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <pre>
     * ip地址
     * </pre>
     *
     * <code>string ip_addr = 4;</code>
     */
    java.lang.String getIpAddr();
    /**
     * <pre>
     * ip地址
     * </pre>
     *
     * <code>string ip_addr = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpAddrBytes();

    /**
     * <pre>
     * 应用（产品）版本
     * </pre>
     *
     * <code>string app_ver = 5;</code>
     */
    java.lang.String getAppVer();
    /**
     * <pre>
     * 应用（产品）版本
     * </pre>
     *
     * <code>string app_ver = 5;</code>
     */
    com.google.protobuf.ByteString
        getAppVerBytes();

    /**
     * <pre>
     * 异常堆栈信息
     * </pre>
     *
     * <code>string error = 6;</code>
     */
    java.lang.String getError();
    /**
     * <pre>
     * 异常堆栈信息
     * </pre>
     *
     * <code>string error = 6;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <pre>
     * 发生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 7;</code>
     */
    java.lang.String getErrTs();
    /**
     * <pre>
     * 发生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 7;</code>
     */
    com.google.protobuf.ByteString
        getErrTsBytes();
  }
  /**
   * <pre>
   *err的PB数据
   * </pre>
   *
   * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv2.Err}
   */
  public  static final class Err extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.autoai.wedata.kittx.uds.log.bean.pbv2.Err)
      ErrOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Err.newBuilder() to construct.
    private Err(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Err() {
      deviceId_ = "";
      appId_ = "";
      sessionId_ = "";
      ipAddr_ = "";
      appVer_ = "";
      error_ = "";
      errTs_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Err(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ipAddr_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              appVer_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              errTs_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err.class, com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err.Builder.class);
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <pre>
     * 终端唯一识别号
     * </pre>
     *
     * <code>string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 终端唯一识别号
     * </pre>
     *
     * <code>string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object appId_;
    /**
     * <pre>
     * 应用（产品）唯一标识
     * </pre>
     *
     * <code>string app_id = 2;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 应用（产品）唯一标识
     * </pre>
     *
     * <code>string app_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object sessionId_;
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string session_id = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string session_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_ADDR_FIELD_NUMBER = 4;
    private volatile java.lang.Object ipAddr_;
    /**
     * <pre>
     * ip地址
     * </pre>
     *
     * <code>string ip_addr = 4;</code>
     */
    public java.lang.String getIpAddr() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ip地址
     * </pre>
     *
     * <code>string ip_addr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddrBytes() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_VER_FIELD_NUMBER = 5;
    private volatile java.lang.Object appVer_;
    /**
     * <pre>
     * 应用（产品）版本
     * </pre>
     *
     * <code>string app_ver = 5;</code>
     */
    public java.lang.String getAppVer() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 应用（产品）版本
     * </pre>
     *
     * <code>string app_ver = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAppVerBytes() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 6;
    private volatile java.lang.Object error_;
    /**
     * <pre>
     * 异常堆栈信息
     * </pre>
     *
     * <code>string error = 6;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 异常堆栈信息
     * </pre>
     *
     * <code>string error = 6;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERR_TS_FIELD_NUMBER = 7;
    private volatile java.lang.Object errTs_;
    /**
     * <pre>
     * 发生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 7;</code>
     */
    public java.lang.String getErrTs() {
      java.lang.Object ref = errTs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errTs_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 7;</code>
     */
    public com.google.protobuf.ByteString
        getErrTsBytes() {
      java.lang.Object ref = errTs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errTs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appId_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
      }
      if (!getIpAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ipAddr_);
      }
      if (!getAppVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appVer_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, error_);
      }
      if (!getErrTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, errTs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appId_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
      }
      if (!getIpAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ipAddr_);
      }
      if (!getAppVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appVer_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, error_);
      }
      if (!getErrTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, errTs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err)) {
        return super.equals(obj);
      }
      com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err other = (com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err) obj;

      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (!getAppId()
          .equals(other.getAppId())) return false;
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (!getIpAddr()
          .equals(other.getIpAddr())) return false;
      if (!getAppVer()
          .equals(other.getAppVer())) return false;
      if (!getError()
          .equals(other.getError())) return false;
      if (!getErrTs()
          .equals(other.getErrTs())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + IP_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddr().hashCode();
      hash = (37 * hash) + APP_VER_FIELD_NUMBER;
      hash = (53 * hash) + getAppVer().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (37 * hash) + ERR_TS_FIELD_NUMBER;
      hash = (53 * hash) + getErrTs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *err的PB数据
     * </pre>
     *
     * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv2.Err}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autoai.wedata.kittx.uds.log.bean.pbv2.Err)
        com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.ErrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err.class, com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err.Builder.class);
      }

      // Construct using com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        appId_ = "";

        sessionId_ = "";

        ipAddr_ = "";

        appVer_ = "";

        error_ = "";

        errTs_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_descriptor;
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err getDefaultInstanceForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err.getDefaultInstance();
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err build() {
        com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err buildPartial() {
        com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err result = new com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err(this);
        result.deviceId_ = deviceId_;
        result.appId_ = appId_;
        result.sessionId_ = sessionId_;
        result.ipAddr_ = ipAddr_;
        result.appVer_ = appVer_;
        result.error_ = error_;
        result.errTs_ = errTs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err) {
          return mergeFrom((com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err other) {
        if (other == com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (!other.getIpAddr().isEmpty()) {
          ipAddr_ = other.ipAddr_;
          onChanged();
        }
        if (!other.getAppVer().isEmpty()) {
          appVer_ = other.appVer_;
          onChanged();
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        if (!other.getErrTs().isEmpty()) {
          errTs_ = other.errTs_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <pre>
       * 终端唯一识别号
       * </pre>
       *
       * <code>string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 终端唯一识别号
       * </pre>
       *
       * <code>string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 终端唯一识别号
       * </pre>
       *
       * <code>string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端唯一识别号
       * </pre>
       *
       * <code>string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端唯一识别号
       * </pre>
       *
       * <code>string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <pre>
       * 应用（产品）唯一标识
       * </pre>
       *
       * <code>string app_id = 2;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 应用（产品）唯一标识
       * </pre>
       *
       * <code>string app_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 应用（产品）唯一标识
       * </pre>
       *
       * <code>string app_id = 2;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用（产品）唯一标识
       * </pre>
       *
       * <code>string app_id = 2;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用（产品）唯一标识
       * </pre>
       *
       * <code>string app_id = 2;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <pre>
       * 会话ID
       * </pre>
       *
       * <code>string session_id = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 会话ID
       * </pre>
       *
       * <code>string session_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 会话ID
       * </pre>
       *
       * <code>string session_id = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话ID
       * </pre>
       *
       * <code>string session_id = 3;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话ID
       * </pre>
       *
       * <code>string session_id = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ipAddr_ = "";
      /**
       * <pre>
       * ip地址
       * </pre>
       *
       * <code>string ip_addr = 4;</code>
       */
      public java.lang.String getIpAddr() {
        java.lang.Object ref = ipAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ip地址
       * </pre>
       *
       * <code>string ip_addr = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddrBytes() {
        java.lang.Object ref = ipAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ip地址
       * </pre>
       *
       * <code>string ip_addr = 4;</code>
       */
      public Builder setIpAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ip地址
       * </pre>
       *
       * <code>string ip_addr = 4;</code>
       */
      public Builder clearIpAddr() {
        
        ipAddr_ = getDefaultInstance().getIpAddr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ip地址
       * </pre>
       *
       * <code>string ip_addr = 4;</code>
       */
      public Builder setIpAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipAddr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appVer_ = "";
      /**
       * <pre>
       * 应用（产品）版本
       * </pre>
       *
       * <code>string app_ver = 5;</code>
       */
      public java.lang.String getAppVer() {
        java.lang.Object ref = appVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 应用（产品）版本
       * </pre>
       *
       * <code>string app_ver = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAppVerBytes() {
        java.lang.Object ref = appVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 应用（产品）版本
       * </pre>
       *
       * <code>string app_ver = 5;</code>
       */
      public Builder setAppVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用（产品）版本
       * </pre>
       *
       * <code>string app_ver = 5;</code>
       */
      public Builder clearAppVer() {
        
        appVer_ = getDefaultInstance().getAppVer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用（产品）版本
       * </pre>
       *
       * <code>string app_ver = 5;</code>
       */
      public Builder setAppVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <pre>
       * 异常堆栈信息
       * </pre>
       *
       * <code>string error = 6;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 异常堆栈信息
       * </pre>
       *
       * <code>string error = 6;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 异常堆栈信息
       * </pre>
       *
       * <code>string error = 6;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 异常堆栈信息
       * </pre>
       *
       * <code>string error = 6;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 异常堆栈信息
       * </pre>
       *
       * <code>string error = 6;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errTs_ = "";
      /**
       * <pre>
       * 发生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 7;</code>
       */
      public java.lang.String getErrTs() {
        java.lang.Object ref = errTs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errTs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 7;</code>
       */
      public com.google.protobuf.ByteString
          getErrTsBytes() {
        java.lang.Object ref = errTs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 7;</code>
       */
      public Builder setErrTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 7;</code>
       */
      public Builder clearErrTs() {
        
        errTs_ = getDefaultInstance().getErrTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 7;</code>
       */
      public Builder setErrTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errTs_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.autoai.wedata.kittx.uds.log.bean.pbv2.Err)
    }

    // @@protoc_insertion_point(class_scope:com.autoai.wedata.kittx.uds.log.bean.pbv2.Err)
    private static final com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err();
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Err>
        PARSER = new com.google.protobuf.AbstractParser<Err>() {
      @java.lang.Override
      public Err parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Err(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Err> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Err> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.autoai.wedata.kittx.uds.log.bean.pbv2.ErrBean.Err getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\terr.proto\022)com.autoai.wedata.kittx.uds" +
      ".log.bean.pbv2\"}\n\003Err\022\021\n\tdevice_id\030\001 \001(\t" +
      "\022\016\n\006app_id\030\002 \001(\t\022\022\n\nsession_id\030\003 \001(\t\022\017\n\007" +
      "ip_addr\030\004 \001(\t\022\017\n\007app_ver\030\005 \001(\t\022\r\n\005error\030" +
      "\006 \001(\t\022\016\n\006err_ts\030\007 \001(\tB\tB\007ErrBeanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Err_descriptor,
        new java.lang.String[] { "DeviceId", "AppId", "SessionId", "IpAddr", "AppVer", "Error", "ErrTs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
