// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evt.proto

package com.autoai.wedata.kittx.uds.log.bean.pbv2;

public final class EvtBean {
  private EvtBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EvtOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autoai.wedata.kittx.uds.log.bean.pbv2.Evt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 事件唯一标识
     * </pre>
     *
     * <code>string evt_code = 1;</code>
     */
    java.lang.String getEvtCode();
    /**
     * <pre>
     * 事件唯一标识
     * </pre>
     *
     * <code>string evt_code = 1;</code>
     */
    com.google.protobuf.ByteString
        getEvtCodeBytes();

    /**
     * <pre>
     * 点击目标事件时间
     * </pre>
     *
     * <code>string evt_beg_ts = 2;</code>
     */
    java.lang.String getEvtBegTs();
    /**
     * <pre>
     * 点击目标事件时间
     * </pre>
     *
     * <code>string evt_beg_ts = 2;</code>
     */
    com.google.protobuf.ByteString
        getEvtBegTsBytes();

    /**
     * <pre>
     * 离开目标事件时间
     * </pre>
     *
     * <code>string evt_end_ts = 3;</code>
     */
    java.lang.String getEvtEndTs();
    /**
     * <pre>
     * 离开目标事件时间
     * </pre>
     *
     * <code>string evt_end_ts = 3;</code>
     */
    com.google.protobuf.ByteString
        getEvtEndTsBytes();

    /**
     * <pre>
     * 人机交互方式
     * </pre>
     *
     * <code>string touch_type = 4;</code>
     */
    java.lang.String getTouchType();
    /**
     * <pre>
     * 人机交互方式
     * </pre>
     *
     * <code>string touch_type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTouchTypeBytes();

    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail> 
        getEvtDetailList();
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail getEvtDetail(int index);
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    int getEvtDetailCount();
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder> 
        getEvtDetailOrBuilderList();
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder getEvtDetailOrBuilder(
        int index);
  }
  /**
   * <pre>
   *evt的PB数据
   * </pre>
   *
   * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv2.Evt}
   */
  public  static final class Evt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.autoai.wedata.kittx.uds.log.bean.pbv2.Evt)
      EvtOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Evt.newBuilder() to construct.
    private Evt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Evt() {
      evtCode_ = "";
      evtBegTs_ = "";
      evtEndTs_ = "";
      touchType_ = "";
      evtDetail_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Evt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              evtCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              evtBegTs_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              evtEndTs_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              touchType_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                evtDetail_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail>();
                mutable_bitField0_ |= 0x00000010;
              }
              evtDetail_.add(
                  input.readMessage(com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          evtDetail_ = java.util.Collections.unmodifiableList(evtDetail_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt.class, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt.Builder.class);
    }

    private int bitField0_;
    public static final int EVT_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object evtCode_;
    /**
     * <pre>
     * 事件唯一标识
     * </pre>
     *
     * <code>string evt_code = 1;</code>
     */
    public java.lang.String getEvtCode() {
      java.lang.Object ref = evtCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        evtCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 事件唯一标识
     * </pre>
     *
     * <code>string evt_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEvtCodeBytes() {
      java.lang.Object ref = evtCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        evtCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVT_BEG_TS_FIELD_NUMBER = 2;
    private volatile java.lang.Object evtBegTs_;
    /**
     * <pre>
     * 点击目标事件时间
     * </pre>
     *
     * <code>string evt_beg_ts = 2;</code>
     */
    public java.lang.String getEvtBegTs() {
      java.lang.Object ref = evtBegTs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        evtBegTs_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 点击目标事件时间
     * </pre>
     *
     * <code>string evt_beg_ts = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEvtBegTsBytes() {
      java.lang.Object ref = evtBegTs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        evtBegTs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVT_END_TS_FIELD_NUMBER = 3;
    private volatile java.lang.Object evtEndTs_;
    /**
     * <pre>
     * 离开目标事件时间
     * </pre>
     *
     * <code>string evt_end_ts = 3;</code>
     */
    public java.lang.String getEvtEndTs() {
      java.lang.Object ref = evtEndTs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        evtEndTs_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 离开目标事件时间
     * </pre>
     *
     * <code>string evt_end_ts = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEvtEndTsBytes() {
      java.lang.Object ref = evtEndTs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        evtEndTs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUCH_TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object touchType_;
    /**
     * <pre>
     * 人机交互方式
     * </pre>
     *
     * <code>string touch_type = 4;</code>
     */
    public java.lang.String getTouchType() {
      java.lang.Object ref = touchType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        touchType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 人机交互方式
     * </pre>
     *
     * <code>string touch_type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTouchTypeBytes() {
      java.lang.Object ref = touchType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        touchType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVT_DETAIL_FIELD_NUMBER = 5;
    private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail> evtDetail_;
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail> getEvtDetailList() {
      return evtDetail_;
    }
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder> 
        getEvtDetailOrBuilderList() {
      return evtDetail_;
    }
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    public int getEvtDetailCount() {
      return evtDetail_.size();
    }
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail getEvtDetail(int index) {
      return evtDetail_.get(index);
    }
    /**
     * <pre>
     * 引入页面的值
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder getEvtDetailOrBuilder(
        int index) {
      return evtDetail_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEvtCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, evtCode_);
      }
      if (!getEvtBegTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, evtBegTs_);
      }
      if (!getEvtEndTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, evtEndTs_);
      }
      if (!getTouchTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, touchType_);
      }
      for (int i = 0; i < evtDetail_.size(); i++) {
        output.writeMessage(5, evtDetail_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEvtCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, evtCode_);
      }
      if (!getEvtBegTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, evtBegTs_);
      }
      if (!getEvtEndTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, evtEndTs_);
      }
      if (!getTouchTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, touchType_);
      }
      for (int i = 0; i < evtDetail_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, evtDetail_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt)) {
        return super.equals(obj);
      }
      com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt other = (com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt) obj;

      if (!getEvtCode()
          .equals(other.getEvtCode())) return false;
      if (!getEvtBegTs()
          .equals(other.getEvtBegTs())) return false;
      if (!getEvtEndTs()
          .equals(other.getEvtEndTs())) return false;
      if (!getTouchType()
          .equals(other.getTouchType())) return false;
      if (!getEvtDetailList()
          .equals(other.getEvtDetailList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVT_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getEvtCode().hashCode();
      hash = (37 * hash) + EVT_BEG_TS_FIELD_NUMBER;
      hash = (53 * hash) + getEvtBegTs().hashCode();
      hash = (37 * hash) + EVT_END_TS_FIELD_NUMBER;
      hash = (53 * hash) + getEvtEndTs().hashCode();
      hash = (37 * hash) + TOUCH_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTouchType().hashCode();
      if (getEvtDetailCount() > 0) {
        hash = (37 * hash) + EVT_DETAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEvtDetailList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *evt的PB数据
     * </pre>
     *
     * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv2.Evt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autoai.wedata.kittx.uds.log.bean.pbv2.Evt)
        com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.EvtOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt.class, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt.Builder.class);
      }

      // Construct using com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEvtDetailFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        evtCode_ = "";

        evtBegTs_ = "";

        evtEndTs_ = "";

        touchType_ = "";

        if (evtDetailBuilder_ == null) {
          evtDetail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          evtDetailBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_descriptor;
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt getDefaultInstanceForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt.getDefaultInstance();
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt build() {
        com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt buildPartial() {
        com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt result = new com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.evtCode_ = evtCode_;
        result.evtBegTs_ = evtBegTs_;
        result.evtEndTs_ = evtEndTs_;
        result.touchType_ = touchType_;
        if (evtDetailBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            evtDetail_ = java.util.Collections.unmodifiableList(evtDetail_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.evtDetail_ = evtDetail_;
        } else {
          result.evtDetail_ = evtDetailBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt) {
          return mergeFrom((com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt other) {
        if (other == com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt.getDefaultInstance()) return this;
        if (!other.getEvtCode().isEmpty()) {
          evtCode_ = other.evtCode_;
          onChanged();
        }
        if (!other.getEvtBegTs().isEmpty()) {
          evtBegTs_ = other.evtBegTs_;
          onChanged();
        }
        if (!other.getEvtEndTs().isEmpty()) {
          evtEndTs_ = other.evtEndTs_;
          onChanged();
        }
        if (!other.getTouchType().isEmpty()) {
          touchType_ = other.touchType_;
          onChanged();
        }
        if (evtDetailBuilder_ == null) {
          if (!other.evtDetail_.isEmpty()) {
            if (evtDetail_.isEmpty()) {
              evtDetail_ = other.evtDetail_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureEvtDetailIsMutable();
              evtDetail_.addAll(other.evtDetail_);
            }
            onChanged();
          }
        } else {
          if (!other.evtDetail_.isEmpty()) {
            if (evtDetailBuilder_.isEmpty()) {
              evtDetailBuilder_.dispose();
              evtDetailBuilder_ = null;
              evtDetail_ = other.evtDetail_;
              bitField0_ = (bitField0_ & ~0x00000010);
              evtDetailBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEvtDetailFieldBuilder() : null;
            } else {
              evtDetailBuilder_.addAllMessages(other.evtDetail_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object evtCode_ = "";
      /**
       * <pre>
       * 事件唯一标识
       * </pre>
       *
       * <code>string evt_code = 1;</code>
       */
      public java.lang.String getEvtCode() {
        java.lang.Object ref = evtCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          evtCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 事件唯一标识
       * </pre>
       *
       * <code>string evt_code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEvtCodeBytes() {
        java.lang.Object ref = evtCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          evtCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 事件唯一标识
       * </pre>
       *
       * <code>string evt_code = 1;</code>
       */
      public Builder setEvtCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        evtCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 事件唯一标识
       * </pre>
       *
       * <code>string evt_code = 1;</code>
       */
      public Builder clearEvtCode() {
        
        evtCode_ = getDefaultInstance().getEvtCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 事件唯一标识
       * </pre>
       *
       * <code>string evt_code = 1;</code>
       */
      public Builder setEvtCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        evtCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object evtBegTs_ = "";
      /**
       * <pre>
       * 点击目标事件时间
       * </pre>
       *
       * <code>string evt_beg_ts = 2;</code>
       */
      public java.lang.String getEvtBegTs() {
        java.lang.Object ref = evtBegTs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          evtBegTs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 点击目标事件时间
       * </pre>
       *
       * <code>string evt_beg_ts = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEvtBegTsBytes() {
        java.lang.Object ref = evtBegTs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          evtBegTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 点击目标事件时间
       * </pre>
       *
       * <code>string evt_beg_ts = 2;</code>
       */
      public Builder setEvtBegTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        evtBegTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 点击目标事件时间
       * </pre>
       *
       * <code>string evt_beg_ts = 2;</code>
       */
      public Builder clearEvtBegTs() {
        
        evtBegTs_ = getDefaultInstance().getEvtBegTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 点击目标事件时间
       * </pre>
       *
       * <code>string evt_beg_ts = 2;</code>
       */
      public Builder setEvtBegTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        evtBegTs_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object evtEndTs_ = "";
      /**
       * <pre>
       * 离开目标事件时间
       * </pre>
       *
       * <code>string evt_end_ts = 3;</code>
       */
      public java.lang.String getEvtEndTs() {
        java.lang.Object ref = evtEndTs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          evtEndTs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 离开目标事件时间
       * </pre>
       *
       * <code>string evt_end_ts = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEvtEndTsBytes() {
        java.lang.Object ref = evtEndTs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          evtEndTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 离开目标事件时间
       * </pre>
       *
       * <code>string evt_end_ts = 3;</code>
       */
      public Builder setEvtEndTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        evtEndTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 离开目标事件时间
       * </pre>
       *
       * <code>string evt_end_ts = 3;</code>
       */
      public Builder clearEvtEndTs() {
        
        evtEndTs_ = getDefaultInstance().getEvtEndTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 离开目标事件时间
       * </pre>
       *
       * <code>string evt_end_ts = 3;</code>
       */
      public Builder setEvtEndTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        evtEndTs_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object touchType_ = "";
      /**
       * <pre>
       * 人机交互方式
       * </pre>
       *
       * <code>string touch_type = 4;</code>
       */
      public java.lang.String getTouchType() {
        java.lang.Object ref = touchType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          touchType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 人机交互方式
       * </pre>
       *
       * <code>string touch_type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTouchTypeBytes() {
        java.lang.Object ref = touchType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          touchType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 人机交互方式
       * </pre>
       *
       * <code>string touch_type = 4;</code>
       */
      public Builder setTouchType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        touchType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 人机交互方式
       * </pre>
       *
       * <code>string touch_type = 4;</code>
       */
      public Builder clearTouchType() {
        
        touchType_ = getDefaultInstance().getTouchType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 人机交互方式
       * </pre>
       *
       * <code>string touch_type = 4;</code>
       */
      public Builder setTouchTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        touchType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail> evtDetail_ =
        java.util.Collections.emptyList();
      private void ensureEvtDetailIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          evtDetail_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail>(evtDetail_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder> evtDetailBuilder_;

      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail> getEvtDetailList() {
        if (evtDetailBuilder_ == null) {
          return java.util.Collections.unmodifiableList(evtDetail_);
        } else {
          return evtDetailBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public int getEvtDetailCount() {
        if (evtDetailBuilder_ == null) {
          return evtDetail_.size();
        } else {
          return evtDetailBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail getEvtDetail(int index) {
        if (evtDetailBuilder_ == null) {
          return evtDetail_.get(index);
        } else {
          return evtDetailBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder setEvtDetail(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail value) {
        if (evtDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvtDetailIsMutable();
          evtDetail_.set(index, value);
          onChanged();
        } else {
          evtDetailBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder setEvtDetail(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder builderForValue) {
        if (evtDetailBuilder_ == null) {
          ensureEvtDetailIsMutable();
          evtDetail_.set(index, builderForValue.build());
          onChanged();
        } else {
          evtDetailBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder addEvtDetail(com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail value) {
        if (evtDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvtDetailIsMutable();
          evtDetail_.add(value);
          onChanged();
        } else {
          evtDetailBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder addEvtDetail(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail value) {
        if (evtDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvtDetailIsMutable();
          evtDetail_.add(index, value);
          onChanged();
        } else {
          evtDetailBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder addEvtDetail(
          com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder builderForValue) {
        if (evtDetailBuilder_ == null) {
          ensureEvtDetailIsMutable();
          evtDetail_.add(builderForValue.build());
          onChanged();
        } else {
          evtDetailBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder addEvtDetail(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder builderForValue) {
        if (evtDetailBuilder_ == null) {
          ensureEvtDetailIsMutable();
          evtDetail_.add(index, builderForValue.build());
          onChanged();
        } else {
          evtDetailBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder addAllEvtDetail(
          java.lang.Iterable<? extends com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail> values) {
        if (evtDetailBuilder_ == null) {
          ensureEvtDetailIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, evtDetail_);
          onChanged();
        } else {
          evtDetailBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder clearEvtDetail() {
        if (evtDetailBuilder_ == null) {
          evtDetail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          evtDetailBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public Builder removeEvtDetail(int index) {
        if (evtDetailBuilder_ == null) {
          ensureEvtDetailIsMutable();
          evtDetail_.remove(index);
          onChanged();
        } else {
          evtDetailBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder getEvtDetailBuilder(
          int index) {
        return getEvtDetailFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder getEvtDetailOrBuilder(
          int index) {
        if (evtDetailBuilder_ == null) {
          return evtDetail_.get(index);  } else {
          return evtDetailBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder> 
           getEvtDetailOrBuilderList() {
        if (evtDetailBuilder_ != null) {
          return evtDetailBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(evtDetail_);
        }
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder addEvtDetailBuilder() {
        return getEvtDetailFieldBuilder().addBuilder(
            com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.getDefaultInstance());
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder addEvtDetailBuilder(
          int index) {
        return getEvtDetailFieldBuilder().addBuilder(
            index, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.getDefaultInstance());
      }
      /**
       * <pre>
       * 引入页面的值
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetail evt_detail = 5;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder> 
           getEvtDetailBuilderList() {
        return getEvtDetailFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder> 
          getEvtDetailFieldBuilder() {
        if (evtDetailBuilder_ == null) {
          evtDetailBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetail.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.EvtDetailOrBuilder>(
                  evtDetail_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          evtDetail_ = null;
        }
        return evtDetailBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.autoai.wedata.kittx.uds.log.bean.pbv2.Evt)
    }

    // @@protoc_insertion_point(class_scope:com.autoai.wedata.kittx.uds.log.bean.pbv2.Evt)
    private static final com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt();
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Evt>
        PARSER = new com.google.protobuf.AbstractParser<Evt>() {
      @java.lang.Override
      public Evt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Evt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Evt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Evt> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtBean.Evt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tevt.proto\022)com.autoai.wedata.kittx.uds" +
      ".log.bean.pbv2\032\020evt_detail.proto\"\235\001\n\003Evt" +
      "\022\020\n\010evt_code\030\001 \001(\t\022\022\n\nevt_beg_ts\030\002 \001(\t\022\022" +
      "\n\nevt_end_ts\030\003 \001(\t\022\022\n\ntouch_type\030\004 \001(\t\022H" +
      "\n\nevt_detail\030\005 \003(\01324.com.autoai.wedata.k" +
      "ittx.uds.log.bean.pbv2.EvtDetailB\tB\007EvtB" +
      "eanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.getDescriptor(),
        }, assigner);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv2_Evt_descriptor,
        new java.lang.String[] { "EvtCode", "EvtBegTs", "EvtEndTs", "TouchType", "EvtDetail", });
    com.autoai.wedata.kittx.uds.log.bean.pbv2.EvtDetailBean.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
