// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errorData.proto

package com.autoai.wedata.kittx.uds.log.bean.pbv1;

public final class ErrorDataBean {
  private ErrorDataBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *	app唯一标识
     * </pre>
     *
     * <code>string app_id = 1;</code>
     */
    java.lang.String getAppId();
    /**
     * <pre>
     *	app唯一标识
     * </pre>
     *
     * <code>string app_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <pre>
     *访问IP地址
     * </pre>
     *
     * <code>string ip_addr = 2;</code>
     */
    java.lang.String getIpAddr();
    /**
     * <pre>
     *访问IP地址
     * </pre>
     *
     * <code>string ip_addr = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpAddrBytes();

    /**
     * <pre>
     *app版本号
     * </pre>
     *
     * <code>string app_ver = 3;</code>
     */
    java.lang.String getAppVer();
    /**
     * <pre>
     *app版本号
     * </pre>
     *
     * <code>string app_ver = 3;</code>
     */
    com.google.protobuf.ByteString
        getAppVerBytes();

    /**
     * <pre>
     *出现异常类名（包含路径，方法名）
     * </pre>
     *
     * <code>string package = 4;</code>
     */
    java.lang.String getPackage();
    /**
     * <pre>
     *出现异常类名（包含路径，方法名）
     * </pre>
     *
     * <code>string package = 4;</code>
     */
    com.google.protobuf.ByteString
        getPackageBytes();

    /**
     * <pre>
     *异常堆栈信息
     * </pre>
     *
     * <code>string error = 5;</code>
     */
    java.lang.String getError();
    /**
     * <pre>
     *异常堆栈信息
     * </pre>
     *
     * <code>string error = 5;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <pre>
     *放生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 6;</code>
     */
    java.lang.String getErrTs();
    /**
     * <pre>
     *放生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 6;</code>
     */
    com.google.protobuf.ByteString
        getErrTsBytes();

    /**
     * <pre>
     *拓展
     * </pre>
     *
     * <code>string ext = 7;</code>
     */
    java.lang.String getExt();
    /**
     * <pre>
     *拓展
     * </pre>
     *
     * <code>string ext = 7;</code>
     */
    com.google.protobuf.ByteString
        getExtBytes();
  }
  /**
   * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorData}
   */
  public  static final class ErrorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorData)
      ErrorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ErrorData.newBuilder() to construct.
    private ErrorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorData() {
      appId_ = "";
      ipAddr_ = "";
      appVer_ = "";
      package_ = "";
      error_ = "";
      errTs_ = "";
      ext_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ipAddr_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appVer_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              package_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              errTs_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              ext_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData.class, com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData.Builder.class);
    }

    public static final int APP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object appId_;
    /**
     * <pre>
     *	app唯一标识
     * </pre>
     *
     * <code>string app_id = 1;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *	app唯一标识
     * </pre>
     *
     * <code>string app_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_ADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object ipAddr_;
    /**
     * <pre>
     *访问IP地址
     * </pre>
     *
     * <code>string ip_addr = 2;</code>
     */
    public java.lang.String getIpAddr() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *访问IP地址
     * </pre>
     *
     * <code>string ip_addr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddrBytes() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_VER_FIELD_NUMBER = 3;
    private volatile java.lang.Object appVer_;
    /**
     * <pre>
     *app版本号
     * </pre>
     *
     * <code>string app_ver = 3;</code>
     */
    public java.lang.String getAppVer() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *app版本号
     * </pre>
     *
     * <code>string app_ver = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppVerBytes() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object package_;
    /**
     * <pre>
     *出现异常类名（包含路径，方法名）
     * </pre>
     *
     * <code>string package = 4;</code>
     */
    public java.lang.String getPackage() {
      java.lang.Object ref = package_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        package_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *出现异常类名（包含路径，方法名）
     * </pre>
     *
     * <code>string package = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPackageBytes() {
      java.lang.Object ref = package_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        package_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 5;
    private volatile java.lang.Object error_;
    /**
     * <pre>
     *异常堆栈信息
     * </pre>
     *
     * <code>string error = 5;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *异常堆栈信息
     * </pre>
     *
     * <code>string error = 5;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERR_TS_FIELD_NUMBER = 6;
    private volatile java.lang.Object errTs_;
    /**
     * <pre>
     *放生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 6;</code>
     */
    public java.lang.String getErrTs() {
      java.lang.Object ref = errTs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errTs_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *放生异常时间戳
     * </pre>
     *
     * <code>string err_ts = 6;</code>
     */
    public com.google.protobuf.ByteString
        getErrTsBytes() {
      java.lang.Object ref = errTs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errTs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXT_FIELD_NUMBER = 7;
    private volatile java.lang.Object ext_;
    /**
     * <pre>
     *拓展
     * </pre>
     *
     * <code>string ext = 7;</code>
     */
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *拓展
     * </pre>
     *
     * <code>string ext = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
      }
      if (!getIpAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ipAddr_);
      }
      if (!getAppVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appVer_);
      }
      if (!getPackageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, package_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, error_);
      }
      if (!getErrTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errTs_);
      }
      if (!getExtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ext_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
      }
      if (!getIpAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ipAddr_);
      }
      if (!getAppVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appVer_);
      }
      if (!getPackageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, package_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, error_);
      }
      if (!getErrTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errTs_);
      }
      if (!getExtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ext_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData)) {
        return super.equals(obj);
      }
      com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData other = (com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData) obj;

      if (!getAppId()
          .equals(other.getAppId())) return false;
      if (!getIpAddr()
          .equals(other.getIpAddr())) return false;
      if (!getAppVer()
          .equals(other.getAppVer())) return false;
      if (!getPackage()
          .equals(other.getPackage())) return false;
      if (!getError()
          .equals(other.getError())) return false;
      if (!getErrTs()
          .equals(other.getErrTs())) return false;
      if (!getExt()
          .equals(other.getExt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + IP_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddr().hashCode();
      hash = (37 * hash) + APP_VER_FIELD_NUMBER;
      hash = (53 * hash) + getAppVer().hashCode();
      hash = (37 * hash) + PACKAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPackage().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (37 * hash) + ERR_TS_FIELD_NUMBER;
      hash = (53 * hash) + getErrTs().hashCode();
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + getExt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorData)
        com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData.class, com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData.Builder.class);
      }

      // Construct using com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appId_ = "";

        ipAddr_ = "";

        appVer_ = "";

        package_ = "";

        error_ = "";

        errTs_ = "";

        ext_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_descriptor;
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData getDefaultInstanceForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData.getDefaultInstance();
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData build() {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData buildPartial() {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData result = new com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData(this);
        result.appId_ = appId_;
        result.ipAddr_ = ipAddr_;
        result.appVer_ = appVer_;
        result.package_ = package_;
        result.error_ = error_;
        result.errTs_ = errTs_;
        result.ext_ = ext_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData) {
          return mergeFrom((com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData other) {
        if (other == com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData.getDefaultInstance()) return this;
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (!other.getIpAddr().isEmpty()) {
          ipAddr_ = other.ipAddr_;
          onChanged();
        }
        if (!other.getAppVer().isEmpty()) {
          appVer_ = other.appVer_;
          onChanged();
        }
        if (!other.getPackage().isEmpty()) {
          package_ = other.package_;
          onChanged();
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        if (!other.getErrTs().isEmpty()) {
          errTs_ = other.errTs_;
          onChanged();
        }
        if (!other.getExt().isEmpty()) {
          ext_ = other.ext_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <pre>
       *	app唯一标识
       * </pre>
       *
       * <code>string app_id = 1;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *	app唯一标识
       * </pre>
       *
       * <code>string app_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *	app唯一标识
       * </pre>
       *
       * <code>string app_id = 1;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	app唯一标识
       * </pre>
       *
       * <code>string app_id = 1;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	app唯一标识
       * </pre>
       *
       * <code>string app_id = 1;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ipAddr_ = "";
      /**
       * <pre>
       *访问IP地址
       * </pre>
       *
       * <code>string ip_addr = 2;</code>
       */
      public java.lang.String getIpAddr() {
        java.lang.Object ref = ipAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *访问IP地址
       * </pre>
       *
       * <code>string ip_addr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddrBytes() {
        java.lang.Object ref = ipAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *访问IP地址
       * </pre>
       *
       * <code>string ip_addr = 2;</code>
       */
      public Builder setIpAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *访问IP地址
       * </pre>
       *
       * <code>string ip_addr = 2;</code>
       */
      public Builder clearIpAddr() {
        
        ipAddr_ = getDefaultInstance().getIpAddr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *访问IP地址
       * </pre>
       *
       * <code>string ip_addr = 2;</code>
       */
      public Builder setIpAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipAddr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appVer_ = "";
      /**
       * <pre>
       *app版本号
       * </pre>
       *
       * <code>string app_ver = 3;</code>
       */
      public java.lang.String getAppVer() {
        java.lang.Object ref = appVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *app版本号
       * </pre>
       *
       * <code>string app_ver = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAppVerBytes() {
        java.lang.Object ref = appVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *app版本号
       * </pre>
       *
       * <code>string app_ver = 3;</code>
       */
      public Builder setAppVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *app版本号
       * </pre>
       *
       * <code>string app_ver = 3;</code>
       */
      public Builder clearAppVer() {
        
        appVer_ = getDefaultInstance().getAppVer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *app版本号
       * </pre>
       *
       * <code>string app_ver = 3;</code>
       */
      public Builder setAppVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object package_ = "";
      /**
       * <pre>
       *出现异常类名（包含路径，方法名）
       * </pre>
       *
       * <code>string package = 4;</code>
       */
      public java.lang.String getPackage() {
        java.lang.Object ref = package_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          package_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *出现异常类名（包含路径，方法名）
       * </pre>
       *
       * <code>string package = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPackageBytes() {
        java.lang.Object ref = package_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          package_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *出现异常类名（包含路径，方法名）
       * </pre>
       *
       * <code>string package = 4;</code>
       */
      public Builder setPackage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        package_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *出现异常类名（包含路径，方法名）
       * </pre>
       *
       * <code>string package = 4;</code>
       */
      public Builder clearPackage() {
        
        package_ = getDefaultInstance().getPackage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *出现异常类名（包含路径，方法名）
       * </pre>
       *
       * <code>string package = 4;</code>
       */
      public Builder setPackageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        package_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <pre>
       *异常堆栈信息
       * </pre>
       *
       * <code>string error = 5;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *异常堆栈信息
       * </pre>
       *
       * <code>string error = 5;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *异常堆栈信息
       * </pre>
       *
       * <code>string error = 5;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *异常堆栈信息
       * </pre>
       *
       * <code>string error = 5;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *异常堆栈信息
       * </pre>
       *
       * <code>string error = 5;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errTs_ = "";
      /**
       * <pre>
       *放生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 6;</code>
       */
      public java.lang.String getErrTs() {
        java.lang.Object ref = errTs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errTs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *放生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 6;</code>
       */
      public com.google.protobuf.ByteString
          getErrTsBytes() {
        java.lang.Object ref = errTs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *放生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 6;</code>
       */
      public Builder setErrTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *放生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 6;</code>
       */
      public Builder clearErrTs() {
        
        errTs_ = getDefaultInstance().getErrTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *放生异常时间戳
       * </pre>
       *
       * <code>string err_ts = 6;</code>
       */
      public Builder setErrTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errTs_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ext_ = "";
      /**
       * <pre>
       *拓展
       * </pre>
       *
       * <code>string ext = 7;</code>
       */
      public java.lang.String getExt() {
        java.lang.Object ref = ext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *拓展
       * </pre>
       *
       * <code>string ext = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        java.lang.Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *拓展
       * </pre>
       *
       * <code>string ext = 7;</code>
       */
      public Builder setExt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ext_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *拓展
       * </pre>
       *
       * <code>string ext = 7;</code>
       */
      public Builder clearExt() {
        
        ext_ = getDefaultInstance().getExt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *拓展
       * </pre>
       *
       * <code>string ext = 7;</code>
       */
      public Builder setExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ext_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorData)
    }

    // @@protoc_insertion_point(class_scope:com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorData)
    private static final com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData();
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorData>
        PARSER = new com.google.protobuf.AbstractParser<ErrorData>() {
      public ErrorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorData> getParserForType() {
      return PARSER;
    }

    public com.autoai.wedata.kittx.uds.log.bean.pbv1.ErrorDataBean.ErrorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017errorData.proto\022)com.autoai.wedata.kit" +
      "tx.uds.log.bean.pbv1\"z\n\tErrorData\022\016\n\006app" +
      "_id\030\001 \001(\t\022\017\n\007ip_addr\030\002 \001(\t\022\017\n\007app_ver\030\003 " +
      "\001(\t\022\017\n\007package\030\004 \001(\t\022\r\n\005error\030\005 \001(\t\022\016\n\006e" +
      "rr_ts\030\006 \001(\t\022\013\n\003ext\030\007 \001(\tB\017B\rErrorDataBea" +
      "nb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_ErrorData_descriptor,
        new java.lang.String[] { "AppId", "IpAddr", "AppVer", "Package", "Error", "ErrTs", "Ext", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
