// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logData.proto

package com.autoai.wedata.kittx.uds.log.bean.pbv1;

public final class LogDataBean {
  private LogDataBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autoai.wedata.kittx.uds.log.bean.pbv1.LogData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *	采集数据流
     * </pre>
     *
     * <code>repeated bytes originData = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getOriginDataList();
    /**
     * <pre>
     *	采集数据流
     * </pre>
     *
     * <code>repeated bytes originData = 1;</code>
     */
    int getOriginDataCount();
    /**
     * <pre>
     *	采集数据流
     * </pre>
     *
     * <code>repeated bytes originData = 1;</code>
     */
    com.google.protobuf.ByteString getOriginData(int index);

    /**
     * <pre>
     *appkey
     * </pre>
     *
     * <code>string appkey = 2;</code>
     */
    java.lang.String getAppkey();
    /**
     * <pre>
     *appkey
     * </pre>
     *
     * <code>string appkey = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppkeyBytes();

    /**
     * <pre>
     *数据长度
     * </pre>
     *
     * <code>string dataLength = 3;</code>
     */
    java.lang.String getDataLength();
    /**
     * <pre>
     *数据长度
     * </pre>
     *
     * <code>string dataLength = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataLengthBytes();

    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>string signature = 4;</code>
     */
    java.lang.String getSignature();
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>string signature = 4;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <pre>
     *版本信息
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    java.lang.String getVersion();
    /**
     * <pre>
     *版本信息
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string ts = 6;</code>
     */
    java.lang.String getTs();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string ts = 6;</code>
     */
    com.google.protobuf.ByteString
        getTsBytes();
  }
  /**
   * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv1.LogData}
   */
  public  static final class LogData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.autoai.wedata.kittx.uds.log.bean.pbv1.LogData)
      LogDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogData.newBuilder() to construct.
    private LogData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogData() {
      originData_ = java.util.Collections.emptyList();
      appkey_ = "";
      dataLength_ = "";
      signature_ = "";
      version_ = "";
      ts_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                originData_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              originData_.add(input.readBytes());
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appkey_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              dataLength_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              ts_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          originData_ = java.util.Collections.unmodifiableList(originData_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData.class, com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData.Builder.class);
    }

    private int bitField0_;
    public static final int ORIGINDATA_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> originData_;
    /**
     * <pre>
     *	采集数据流
     * </pre>
     *
     * <code>repeated bytes originData = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getOriginDataList() {
      return originData_;
    }
    /**
     * <pre>
     *	采集数据流
     * </pre>
     *
     * <code>repeated bytes originData = 1;</code>
     */
    public int getOriginDataCount() {
      return originData_.size();
    }
    /**
     * <pre>
     *	采集数据流
     * </pre>
     *
     * <code>repeated bytes originData = 1;</code>
     */
    public com.google.protobuf.ByteString getOriginData(int index) {
      return originData_.get(index);
    }

    public static final int APPKEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object appkey_;
    /**
     * <pre>
     *appkey
     * </pre>
     *
     * <code>string appkey = 2;</code>
     */
    public java.lang.String getAppkey() {
      java.lang.Object ref = appkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appkey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *appkey
     * </pre>
     *
     * <code>string appkey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      java.lang.Object ref = appkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATALENGTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object dataLength_;
    /**
     * <pre>
     *数据长度
     * </pre>
     *
     * <code>string dataLength = 3;</code>
     */
    public java.lang.String getDataLength() {
      java.lang.Object ref = dataLength_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataLength_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *数据长度
     * </pre>
     *
     * <code>string dataLength = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataLengthBytes() {
      java.lang.Object ref = dataLength_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataLength_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 4;
    private volatile java.lang.Object signature_;
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>string signature = 4;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>string signature = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private volatile java.lang.Object version_;
    /**
     * <pre>
     *版本信息
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *版本信息
     * </pre>
     *
     * <code>string version = 5;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 6;
    private volatile java.lang.Object ts_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string ts = 6;</code>
     */
    public java.lang.String getTs() {
      java.lang.Object ref = ts_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ts_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string ts = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTsBytes() {
      java.lang.Object ref = ts_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < originData_.size(); i++) {
        output.writeBytes(1, originData_.get(i));
      }
      if (!getAppkeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appkey_);
      }
      if (!getDataLengthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataLength_);
      }
      if (!getSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, signature_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, version_);
      }
      if (!getTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ts_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < originData_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(originData_.get(i));
        }
        size += dataSize;
        size += 1 * getOriginDataList().size();
      }
      if (!getAppkeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appkey_);
      }
      if (!getDataLengthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataLength_);
      }
      if (!getSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, signature_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, version_);
      }
      if (!getTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ts_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData)) {
        return super.equals(obj);
      }
      com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData other = (com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData) obj;

      if (!getOriginDataList()
          .equals(other.getOriginDataList())) return false;
      if (!getAppkey()
          .equals(other.getAppkey())) return false;
      if (!getDataLength()
          .equals(other.getDataLength())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getTs()
          .equals(other.getTs())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOriginDataCount() > 0) {
        hash = (37 * hash) + ORIGINDATA_FIELD_NUMBER;
        hash = (53 * hash) + getOriginDataList().hashCode();
      }
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppkey().hashCode();
      hash = (37 * hash) + DATALENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getDataLength().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + getTs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv1.LogData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autoai.wedata.kittx.uds.log.bean.pbv1.LogData)
        com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData.class, com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData.Builder.class);
      }

      // Construct using com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        originData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        appkey_ = "";

        dataLength_ = "";

        signature_ = "";

        version_ = "";

        ts_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_descriptor;
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData getDefaultInstanceForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData.getDefaultInstance();
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData build() {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData buildPartial() {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData result = new com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          originData_ = java.util.Collections.unmodifiableList(originData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.originData_ = originData_;
        result.appkey_ = appkey_;
        result.dataLength_ = dataLength_;
        result.signature_ = signature_;
        result.version_ = version_;
        result.ts_ = ts_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData) {
          return mergeFrom((com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData other) {
        if (other == com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData.getDefaultInstance()) return this;
        if (!other.originData_.isEmpty()) {
          if (originData_.isEmpty()) {
            originData_ = other.originData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOriginDataIsMutable();
            originData_.addAll(other.originData_);
          }
          onChanged();
        }
        if (!other.getAppkey().isEmpty()) {
          appkey_ = other.appkey_;
          onChanged();
        }
        if (!other.getDataLength().isEmpty()) {
          dataLength_ = other.dataLength_;
          onChanged();
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getTs().isEmpty()) {
          ts_ = other.ts_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> originData_ = java.util.Collections.emptyList();
      private void ensureOriginDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          originData_ = new java.util.ArrayList<com.google.protobuf.ByteString>(originData_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *	采集数据流
       * </pre>
       *
       * <code>repeated bytes originData = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getOriginDataList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(originData_) : originData_;
      }
      /**
       * <pre>
       *	采集数据流
       * </pre>
       *
       * <code>repeated bytes originData = 1;</code>
       */
      public int getOriginDataCount() {
        return originData_.size();
      }
      /**
       * <pre>
       *	采集数据流
       * </pre>
       *
       * <code>repeated bytes originData = 1;</code>
       */
      public com.google.protobuf.ByteString getOriginData(int index) {
        return originData_.get(index);
      }
      /**
       * <pre>
       *	采集数据流
       * </pre>
       *
       * <code>repeated bytes originData = 1;</code>
       */
      public Builder setOriginData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOriginDataIsMutable();
        originData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	采集数据流
       * </pre>
       *
       * <code>repeated bytes originData = 1;</code>
       */
      public Builder addOriginData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOriginDataIsMutable();
        originData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	采集数据流
       * </pre>
       *
       * <code>repeated bytes originData = 1;</code>
       */
      public Builder addAllOriginData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureOriginDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, originData_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	采集数据流
       * </pre>
       *
       * <code>repeated bytes originData = 1;</code>
       */
      public Builder clearOriginData() {
        originData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.lang.Object appkey_ = "";
      /**
       * <pre>
       *appkey
       * </pre>
       *
       * <code>string appkey = 2;</code>
       */
      public java.lang.String getAppkey() {
        java.lang.Object ref = appkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *appkey
       * </pre>
       *
       * <code>string appkey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppkeyBytes() {
        java.lang.Object ref = appkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *appkey
       * </pre>
       *
       * <code>string appkey = 2;</code>
       */
      public Builder setAppkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *appkey
       * </pre>
       *
       * <code>string appkey = 2;</code>
       */
      public Builder clearAppkey() {
        
        appkey_ = getDefaultInstance().getAppkey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *appkey
       * </pre>
       *
       * <code>string appkey = 2;</code>
       */
      public Builder setAppkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appkey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataLength_ = "";
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>string dataLength = 3;</code>
       */
      public java.lang.String getDataLength() {
        java.lang.Object ref = dataLength_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataLength_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>string dataLength = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataLengthBytes() {
        java.lang.Object ref = dataLength_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataLength_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>string dataLength = 3;</code>
       */
      public Builder setDataLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>string dataLength = 3;</code>
       */
      public Builder clearDataLength() {
        
        dataLength_ = getDefaultInstance().getDataLength();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>string dataLength = 3;</code>
       */
      public Builder setDataLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataLength_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>string signature = 4;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>string signature = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>string signature = 4;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>string signature = 4;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>string signature = 4;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <pre>
       *版本信息
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *版本信息
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *版本信息
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *版本信息
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *版本信息
       * </pre>
       *
       * <code>string version = 5;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ts_ = "";
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string ts = 6;</code>
       */
      public java.lang.String getTs() {
        java.lang.Object ref = ts_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ts_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string ts = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTsBytes() {
        java.lang.Object ref = ts_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ts_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string ts = 6;</code>
       */
      public Builder setTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string ts = 6;</code>
       */
      public Builder clearTs() {
        
        ts_ = getDefaultInstance().getTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string ts = 6;</code>
       */
      public Builder setTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ts_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.autoai.wedata.kittx.uds.log.bean.pbv1.LogData)
    }

    // @@protoc_insertion_point(class_scope:com.autoai.wedata.kittx.uds.log.bean.pbv1.LogData)
    private static final com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData();
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogData>
        PARSER = new com.google.protobuf.AbstractParser<LogData>() {
      public LogData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogData> getParserForType() {
      return PARSER;
    }

    public com.autoai.wedata.kittx.uds.log.bean.pbv1.LogDataBean.LogData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlogData.proto\022)com.autoai.wedata.kittx" +
      ".uds.log.bean.pbv1\"q\n\007LogData\022\022\n\noriginD" +
      "ata\030\001 \003(\014\022\016\n\006appkey\030\002 \001(\t\022\022\n\ndataLength\030" +
      "\003 \001(\t\022\021\n\tsignature\030\004 \001(\t\022\017\n\007version\030\005 \001(" +
      "\t\022\n\n\002ts\030\006 \001(\tB\rB\013LogDataBeanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_LogData_descriptor,
        new java.lang.String[] { "OriginData", "Appkey", "DataLength", "Signature", "Version", "Ts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
