// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: track.proto

package com.autoai.wedata.kittx.uds.log.bean.pbv1;

public final class TrackBean {
  private TrackBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autoai.wedata.kittx.uds.log.bean.pbv1.Track)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *	会话ID
     * </pre>
     *
     * <code>string session_id = 1;</code>
     */
    java.lang.String getSessionId();
    /**
     * <pre>
     *	会话ID
     * </pre>
     *
     * <code>string session_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <pre>
     *	应用开启时间
     * </pre>
     *
     * <code>string app_start_ts = 2;</code>
     */
    java.lang.String getAppStartTs();
    /**
     * <pre>
     *	应用开启时间
     * </pre>
     *
     * <code>string app_start_ts = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppStartTsBytes();

    /**
     * <pre>
     *	应用退出时间
     * </pre>
     *
     * <code>string app_stop_ts = 3;</code>
     */
    java.lang.String getAppStopTs();
    /**
     * <pre>
     *	应用退出时间
     * </pre>
     *
     * <code>string app_stop_ts = 3;</code>
     */
    com.google.protobuf.ByteString
        getAppStopTsBytes();

    /**
     * <pre>
     *	是否第1次安装
     * </pre>
     *
     * <code>string is_first = 4;</code>
     */
    java.lang.String getIsFirst();
    /**
     * <pre>
     *	是否第1次安装
     * </pre>
     *
     * <code>string is_first = 4;</code>
     */
    com.google.protobuf.ByteString
        getIsFirstBytes();

    /**
     * <pre>
     *	是否有升级
     * </pre>
     *
     * <code>string is_update = 5;</code>
     */
    java.lang.String getIsUpdate();
    /**
     * <pre>
     *	是否有升级
     * </pre>
     *
     * <code>string is_update = 5;</code>
     */
    com.google.protobuf.ByteString
        getIsUpdateBytes();

    /**
     * <pre>
     *是否首日访问
     * </pre>
     *
     * <code>string first_day = 6;</code>
     */
    java.lang.String getFirstDay();
    /**
     * <pre>
     *是否首日访问
     * </pre>
     *
     * <code>string first_day = 6;</code>
     */
    com.google.protobuf.ByteString
        getFirstDayBytes();

    /**
     * <pre>
     *是否第1次使用
     * </pre>
     *
     * <code>string first_use = 7;</code>
     */
    java.lang.String getFirstUse();
    /**
     * <pre>
     *是否第1次使用
     * </pre>
     *
     * <code>string first_use = 7;</code>
     */
    com.google.protobuf.ByteString
        getFirstUseBytes();

    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page> 
        getPageList();
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page getPage(int index);
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    int getPageCount();
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder> 
        getPageOrBuilderList();
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder getPageOrBuilder(
        int index);

    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS> 
        getGpsList();
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS getGps(int index);
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    int getGpsCount();
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder> 
        getGpsOrBuilderList();
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder getGpsOrBuilder(
        int index);

    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt> 
        getEvtList();
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt getEvt(int index);
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    int getEvtCount();
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder> 
        getEvtOrBuilderList();
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder getEvtOrBuilder(
        int index);
  }
  /**
   * <pre>
   *track的PB数据
   * </pre>
   *
   * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv1.Track}
   */
  public  static final class Track extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.autoai.wedata.kittx.uds.log.bean.pbv1.Track)
      TrackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Track.newBuilder() to construct.
    private Track(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Track() {
      sessionId_ = "";
      appStartTs_ = "";
      appStopTs_ = "";
      isFirst_ = "";
      isUpdate_ = "";
      firstDay_ = "";
      firstUse_ = "";
      page_ = java.util.Collections.emptyList();
      gps_ = java.util.Collections.emptyList();
      evt_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Track(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appStartTs_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appStopTs_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              isFirst_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              isUpdate_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              firstDay_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              firstUse_ = s;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) != 0)) {
                page_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page>();
                mutable_bitField0_ |= 0x00000080;
              }
              page_.add(
                  input.readMessage(com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.parser(), extensionRegistry));
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) != 0)) {
                gps_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS>();
                mutable_bitField0_ |= 0x00000100;
              }
              gps_.add(
                  input.readMessage(com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.parser(), extensionRegistry));
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) != 0)) {
                evt_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt>();
                mutable_bitField0_ |= 0x00000200;
              }
              evt_.add(
                  input.readMessage(com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) != 0)) {
          page_ = java.util.Collections.unmodifiableList(page_);
        }
        if (((mutable_bitField0_ & 0x00000100) != 0)) {
          gps_ = java.util.Collections.unmodifiableList(gps_);
        }
        if (((mutable_bitField0_ & 0x00000200) != 0)) {
          evt_ = java.util.Collections.unmodifiableList(evt_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track.class, com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track.Builder.class);
    }

    private int bitField0_;
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sessionId_;
    /**
     * <pre>
     *	会话ID
     * </pre>
     *
     * <code>string session_id = 1;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *	会话ID
     * </pre>
     *
     * <code>string session_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_START_TS_FIELD_NUMBER = 2;
    private volatile java.lang.Object appStartTs_;
    /**
     * <pre>
     *	应用开启时间
     * </pre>
     *
     * <code>string app_start_ts = 2;</code>
     */
    public java.lang.String getAppStartTs() {
      java.lang.Object ref = appStartTs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appStartTs_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *	应用开启时间
     * </pre>
     *
     * <code>string app_start_ts = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppStartTsBytes() {
      java.lang.Object ref = appStartTs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appStartTs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_STOP_TS_FIELD_NUMBER = 3;
    private volatile java.lang.Object appStopTs_;
    /**
     * <pre>
     *	应用退出时间
     * </pre>
     *
     * <code>string app_stop_ts = 3;</code>
     */
    public java.lang.String getAppStopTs() {
      java.lang.Object ref = appStopTs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appStopTs_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *	应用退出时间
     * </pre>
     *
     * <code>string app_stop_ts = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppStopTsBytes() {
      java.lang.Object ref = appStopTs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appStopTs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_FIRST_FIELD_NUMBER = 4;
    private volatile java.lang.Object isFirst_;
    /**
     * <pre>
     *	是否第1次安装
     * </pre>
     *
     * <code>string is_first = 4;</code>
     */
    public java.lang.String getIsFirst() {
      java.lang.Object ref = isFirst_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isFirst_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *	是否第1次安装
     * </pre>
     *
     * <code>string is_first = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIsFirstBytes() {
      java.lang.Object ref = isFirst_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isFirst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_UPDATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object isUpdate_;
    /**
     * <pre>
     *	是否有升级
     * </pre>
     *
     * <code>string is_update = 5;</code>
     */
    public java.lang.String getIsUpdate() {
      java.lang.Object ref = isUpdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isUpdate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *	是否有升级
     * </pre>
     *
     * <code>string is_update = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIsUpdateBytes() {
      java.lang.Object ref = isUpdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isUpdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRST_DAY_FIELD_NUMBER = 6;
    private volatile java.lang.Object firstDay_;
    /**
     * <pre>
     *是否首日访问
     * </pre>
     *
     * <code>string first_day = 6;</code>
     */
    public java.lang.String getFirstDay() {
      java.lang.Object ref = firstDay_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstDay_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *是否首日访问
     * </pre>
     *
     * <code>string first_day = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFirstDayBytes() {
      java.lang.Object ref = firstDay_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstDay_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRST_USE_FIELD_NUMBER = 7;
    private volatile java.lang.Object firstUse_;
    /**
     * <pre>
     *是否第1次使用
     * </pre>
     *
     * <code>string first_use = 7;</code>
     */
    public java.lang.String getFirstUse() {
      java.lang.Object ref = firstUse_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstUse_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *是否第1次使用
     * </pre>
     *
     * <code>string first_use = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFirstUseBytes() {
      java.lang.Object ref = firstUse_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstUse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_FIELD_NUMBER = 8;
    private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page> page_;
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page> getPageList() {
      return page_;
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder> 
        getPageOrBuilderList() {
      return page_;
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    public int getPageCount() {
      return page_.size();
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page getPage(int index) {
      return page_.get(index);
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder getPageOrBuilder(
        int index) {
      return page_.get(index);
    }

    public static final int GPS_FIELD_NUMBER = 9;
    private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS> gps_;
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS> getGpsList() {
      return gps_;
    }
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder> 
        getGpsOrBuilderList() {
      return gps_;
    }
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    public int getGpsCount() {
      return gps_.size();
    }
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS getGps(int index) {
      return gps_.get(index);
    }
    /**
     * <pre>
     *  行程gps点数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder getGpsOrBuilder(
        int index) {
      return gps_.get(index);
    }

    public static final int EVT_FIELD_NUMBER = 10;
    private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt> evt_;
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt> getEvtList() {
      return evt_;
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder> 
        getEvtOrBuilderList() {
      return evt_;
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    public int getEvtCount() {
      return evt_.size();
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt getEvt(int index) {
      return evt_.get(index);
    }
    /**
     * <pre>
     *引入页面的数组
     * </pre>
     *
     * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
     */
    public com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder getEvtOrBuilder(
        int index) {
      return evt_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionId_);
      }
      if (!getAppStartTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appStartTs_);
      }
      if (!getAppStopTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appStopTs_);
      }
      if (!getIsFirstBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, isFirst_);
      }
      if (!getIsUpdateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, isUpdate_);
      }
      if (!getFirstDayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, firstDay_);
      }
      if (!getFirstUseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, firstUse_);
      }
      for (int i = 0; i < page_.size(); i++) {
        output.writeMessage(8, page_.get(i));
      }
      for (int i = 0; i < gps_.size(); i++) {
        output.writeMessage(9, gps_.get(i));
      }
      for (int i = 0; i < evt_.size(); i++) {
        output.writeMessage(10, evt_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionId_);
      }
      if (!getAppStartTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appStartTs_);
      }
      if (!getAppStopTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appStopTs_);
      }
      if (!getIsFirstBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, isFirst_);
      }
      if (!getIsUpdateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, isUpdate_);
      }
      if (!getFirstDayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, firstDay_);
      }
      if (!getFirstUseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, firstUse_);
      }
      for (int i = 0; i < page_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, page_.get(i));
      }
      for (int i = 0; i < gps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, gps_.get(i));
      }
      for (int i = 0; i < evt_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, evt_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track)) {
        return super.equals(obj);
      }
      com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track other = (com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track) obj;

      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (!getAppStartTs()
          .equals(other.getAppStartTs())) return false;
      if (!getAppStopTs()
          .equals(other.getAppStopTs())) return false;
      if (!getIsFirst()
          .equals(other.getIsFirst())) return false;
      if (!getIsUpdate()
          .equals(other.getIsUpdate())) return false;
      if (!getFirstDay()
          .equals(other.getFirstDay())) return false;
      if (!getFirstUse()
          .equals(other.getFirstUse())) return false;
      if (!getPageList()
          .equals(other.getPageList())) return false;
      if (!getGpsList()
          .equals(other.getGpsList())) return false;
      if (!getEvtList()
          .equals(other.getEvtList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + APP_START_TS_FIELD_NUMBER;
      hash = (53 * hash) + getAppStartTs().hashCode();
      hash = (37 * hash) + APP_STOP_TS_FIELD_NUMBER;
      hash = (53 * hash) + getAppStopTs().hashCode();
      hash = (37 * hash) + IS_FIRST_FIELD_NUMBER;
      hash = (53 * hash) + getIsFirst().hashCode();
      hash = (37 * hash) + IS_UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getIsUpdate().hashCode();
      hash = (37 * hash) + FIRST_DAY_FIELD_NUMBER;
      hash = (53 * hash) + getFirstDay().hashCode();
      hash = (37 * hash) + FIRST_USE_FIELD_NUMBER;
      hash = (53 * hash) + getFirstUse().hashCode();
      if (getPageCount() > 0) {
        hash = (37 * hash) + PAGE_FIELD_NUMBER;
        hash = (53 * hash) + getPageList().hashCode();
      }
      if (getGpsCount() > 0) {
        hash = (37 * hash) + GPS_FIELD_NUMBER;
        hash = (53 * hash) + getGpsList().hashCode();
      }
      if (getEvtCount() > 0) {
        hash = (37 * hash) + EVT_FIELD_NUMBER;
        hash = (53 * hash) + getEvtList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *track的PB数据
     * </pre>
     *
     * Protobuf type {@code com.autoai.wedata.kittx.uds.log.bean.pbv1.Track}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autoai.wedata.kittx.uds.log.bean.pbv1.Track)
        com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.TrackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track.class, com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track.Builder.class);
      }

      // Construct using com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPageFieldBuilder();
          getGpsFieldBuilder();
          getEvtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = "";

        appStartTs_ = "";

        appStopTs_ = "";

        isFirst_ = "";

        isUpdate_ = "";

        firstDay_ = "";

        firstUse_ = "";

        if (pageBuilder_ == null) {
          page_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          pageBuilder_.clear();
        }
        if (gpsBuilder_ == null) {
          gps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          gpsBuilder_.clear();
        }
        if (evtBuilder_ == null) {
          evt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          evtBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_descriptor;
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track getDefaultInstanceForType() {
        return com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track.getDefaultInstance();
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track build() {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track buildPartial() {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track result = new com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.sessionId_ = sessionId_;
        result.appStartTs_ = appStartTs_;
        result.appStopTs_ = appStopTs_;
        result.isFirst_ = isFirst_;
        result.isUpdate_ = isUpdate_;
        result.firstDay_ = firstDay_;
        result.firstUse_ = firstUse_;
        if (pageBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0)) {
            page_ = java.util.Collections.unmodifiableList(page_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.page_ = page_;
        } else {
          result.page_ = pageBuilder_.build();
        }
        if (gpsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0)) {
            gps_ = java.util.Collections.unmodifiableList(gps_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.gps_ = gps_;
        } else {
          result.gps_ = gpsBuilder_.build();
        }
        if (evtBuilder_ == null) {
          if (((bitField0_ & 0x00000200) != 0)) {
            evt_ = java.util.Collections.unmodifiableList(evt_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.evt_ = evt_;
        } else {
          result.evt_ = evtBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track) {
          return mergeFrom((com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track other) {
        if (other == com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track.getDefaultInstance()) return this;
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (!other.getAppStartTs().isEmpty()) {
          appStartTs_ = other.appStartTs_;
          onChanged();
        }
        if (!other.getAppStopTs().isEmpty()) {
          appStopTs_ = other.appStopTs_;
          onChanged();
        }
        if (!other.getIsFirst().isEmpty()) {
          isFirst_ = other.isFirst_;
          onChanged();
        }
        if (!other.getIsUpdate().isEmpty()) {
          isUpdate_ = other.isUpdate_;
          onChanged();
        }
        if (!other.getFirstDay().isEmpty()) {
          firstDay_ = other.firstDay_;
          onChanged();
        }
        if (!other.getFirstUse().isEmpty()) {
          firstUse_ = other.firstUse_;
          onChanged();
        }
        if (pageBuilder_ == null) {
          if (!other.page_.isEmpty()) {
            if (page_.isEmpty()) {
              page_ = other.page_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensurePageIsMutable();
              page_.addAll(other.page_);
            }
            onChanged();
          }
        } else {
          if (!other.page_.isEmpty()) {
            if (pageBuilder_.isEmpty()) {
              pageBuilder_.dispose();
              pageBuilder_ = null;
              page_ = other.page_;
              bitField0_ = (bitField0_ & ~0x00000080);
              pageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPageFieldBuilder() : null;
            } else {
              pageBuilder_.addAllMessages(other.page_);
            }
          }
        }
        if (gpsBuilder_ == null) {
          if (!other.gps_.isEmpty()) {
            if (gps_.isEmpty()) {
              gps_ = other.gps_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureGpsIsMutable();
              gps_.addAll(other.gps_);
            }
            onChanged();
          }
        } else {
          if (!other.gps_.isEmpty()) {
            if (gpsBuilder_.isEmpty()) {
              gpsBuilder_.dispose();
              gpsBuilder_ = null;
              gps_ = other.gps_;
              bitField0_ = (bitField0_ & ~0x00000100);
              gpsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGpsFieldBuilder() : null;
            } else {
              gpsBuilder_.addAllMessages(other.gps_);
            }
          }
        }
        if (evtBuilder_ == null) {
          if (!other.evt_.isEmpty()) {
            if (evt_.isEmpty()) {
              evt_ = other.evt_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureEvtIsMutable();
              evt_.addAll(other.evt_);
            }
            onChanged();
          }
        } else {
          if (!other.evt_.isEmpty()) {
            if (evtBuilder_.isEmpty()) {
              evtBuilder_.dispose();
              evtBuilder_ = null;
              evt_ = other.evt_;
              bitField0_ = (bitField0_ & ~0x00000200);
              evtBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEvtFieldBuilder() : null;
            } else {
              evtBuilder_.addAllMessages(other.evt_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sessionId_ = "";
      /**
       * <pre>
       *	会话ID
       * </pre>
       *
       * <code>string session_id = 1;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *	会话ID
       * </pre>
       *
       * <code>string session_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *	会话ID
       * </pre>
       *
       * <code>string session_id = 1;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	会话ID
       * </pre>
       *
       * <code>string session_id = 1;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	会话ID
       * </pre>
       *
       * <code>string session_id = 1;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appStartTs_ = "";
      /**
       * <pre>
       *	应用开启时间
       * </pre>
       *
       * <code>string app_start_ts = 2;</code>
       */
      public java.lang.String getAppStartTs() {
        java.lang.Object ref = appStartTs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appStartTs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *	应用开启时间
       * </pre>
       *
       * <code>string app_start_ts = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppStartTsBytes() {
        java.lang.Object ref = appStartTs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appStartTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *	应用开启时间
       * </pre>
       *
       * <code>string app_start_ts = 2;</code>
       */
      public Builder setAppStartTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appStartTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	应用开启时间
       * </pre>
       *
       * <code>string app_start_ts = 2;</code>
       */
      public Builder clearAppStartTs() {
        
        appStartTs_ = getDefaultInstance().getAppStartTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	应用开启时间
       * </pre>
       *
       * <code>string app_start_ts = 2;</code>
       */
      public Builder setAppStartTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appStartTs_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appStopTs_ = "";
      /**
       * <pre>
       *	应用退出时间
       * </pre>
       *
       * <code>string app_stop_ts = 3;</code>
       */
      public java.lang.String getAppStopTs() {
        java.lang.Object ref = appStopTs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appStopTs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *	应用退出时间
       * </pre>
       *
       * <code>string app_stop_ts = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAppStopTsBytes() {
        java.lang.Object ref = appStopTs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appStopTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *	应用退出时间
       * </pre>
       *
       * <code>string app_stop_ts = 3;</code>
       */
      public Builder setAppStopTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appStopTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	应用退出时间
       * </pre>
       *
       * <code>string app_stop_ts = 3;</code>
       */
      public Builder clearAppStopTs() {
        
        appStopTs_ = getDefaultInstance().getAppStopTs();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	应用退出时间
       * </pre>
       *
       * <code>string app_stop_ts = 3;</code>
       */
      public Builder setAppStopTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appStopTs_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object isFirst_ = "";
      /**
       * <pre>
       *	是否第1次安装
       * </pre>
       *
       * <code>string is_first = 4;</code>
       */
      public java.lang.String getIsFirst() {
        java.lang.Object ref = isFirst_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isFirst_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *	是否第1次安装
       * </pre>
       *
       * <code>string is_first = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIsFirstBytes() {
        java.lang.Object ref = isFirst_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isFirst_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *	是否第1次安装
       * </pre>
       *
       * <code>string is_first = 4;</code>
       */
      public Builder setIsFirst(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isFirst_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	是否第1次安装
       * </pre>
       *
       * <code>string is_first = 4;</code>
       */
      public Builder clearIsFirst() {
        
        isFirst_ = getDefaultInstance().getIsFirst();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	是否第1次安装
       * </pre>
       *
       * <code>string is_first = 4;</code>
       */
      public Builder setIsFirstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isFirst_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object isUpdate_ = "";
      /**
       * <pre>
       *	是否有升级
       * </pre>
       *
       * <code>string is_update = 5;</code>
       */
      public java.lang.String getIsUpdate() {
        java.lang.Object ref = isUpdate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isUpdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *	是否有升级
       * </pre>
       *
       * <code>string is_update = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIsUpdateBytes() {
        java.lang.Object ref = isUpdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isUpdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *	是否有升级
       * </pre>
       *
       * <code>string is_update = 5;</code>
       */
      public Builder setIsUpdate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	是否有升级
       * </pre>
       *
       * <code>string is_update = 5;</code>
       */
      public Builder clearIsUpdate() {
        
        isUpdate_ = getDefaultInstance().getIsUpdate();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *	是否有升级
       * </pre>
       *
       * <code>string is_update = 5;</code>
       */
      public Builder setIsUpdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isUpdate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firstDay_ = "";
      /**
       * <pre>
       *是否首日访问
       * </pre>
       *
       * <code>string first_day = 6;</code>
       */
      public java.lang.String getFirstDay() {
        java.lang.Object ref = firstDay_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstDay_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *是否首日访问
       * </pre>
       *
       * <code>string first_day = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFirstDayBytes() {
        java.lang.Object ref = firstDay_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstDay_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *是否首日访问
       * </pre>
       *
       * <code>string first_day = 6;</code>
       */
      public Builder setFirstDay(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否首日访问
       * </pre>
       *
       * <code>string first_day = 6;</code>
       */
      public Builder clearFirstDay() {
        
        firstDay_ = getDefaultInstance().getFirstDay();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否首日访问
       * </pre>
       *
       * <code>string first_day = 6;</code>
       */
      public Builder setFirstDayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstDay_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firstUse_ = "";
      /**
       * <pre>
       *是否第1次使用
       * </pre>
       *
       * <code>string first_use = 7;</code>
       */
      public java.lang.String getFirstUse() {
        java.lang.Object ref = firstUse_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstUse_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *是否第1次使用
       * </pre>
       *
       * <code>string first_use = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFirstUseBytes() {
        java.lang.Object ref = firstUse_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstUse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *是否第1次使用
       * </pre>
       *
       * <code>string first_use = 7;</code>
       */
      public Builder setFirstUse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstUse_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否第1次使用
       * </pre>
       *
       * <code>string first_use = 7;</code>
       */
      public Builder clearFirstUse() {
        
        firstUse_ = getDefaultInstance().getFirstUse();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否第1次使用
       * </pre>
       *
       * <code>string first_use = 7;</code>
       */
      public Builder setFirstUseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstUse_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page> page_ =
        java.util.Collections.emptyList();
      private void ensurePageIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          page_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page>(page_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder> pageBuilder_;

      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page> getPageList() {
        if (pageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(page_);
        } else {
          return pageBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public int getPageCount() {
        if (pageBuilder_ == null) {
          return page_.size();
        } else {
          return pageBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page getPage(int index) {
        if (pageBuilder_ == null) {
          return page_.get(index);
        } else {
          return pageBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder setPage(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page value) {
        if (pageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageIsMutable();
          page_.set(index, value);
          onChanged();
        } else {
          pageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder setPage(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder builderForValue) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.set(index, builderForValue.build());
          onChanged();
        } else {
          pageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder addPage(com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page value) {
        if (pageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageIsMutable();
          page_.add(value);
          onChanged();
        } else {
          pageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder addPage(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page value) {
        if (pageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageIsMutable();
          page_.add(index, value);
          onChanged();
        } else {
          pageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder addPage(
          com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder builderForValue) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.add(builderForValue.build());
          onChanged();
        } else {
          pageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder addPage(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder builderForValue) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.add(index, builderForValue.build());
          onChanged();
        } else {
          pageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder addAllPage(
          java.lang.Iterable<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page> values) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, page_);
          onChanged();
        } else {
          pageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder clearPage() {
        if (pageBuilder_ == null) {
          page_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          pageBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public Builder removePage(int index) {
        if (pageBuilder_ == null) {
          ensurePageIsMutable();
          page_.remove(index);
          onChanged();
        } else {
          pageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder getPageBuilder(
          int index) {
        return getPageFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder getPageOrBuilder(
          int index) {
        if (pageBuilder_ == null) {
          return page_.get(index);  } else {
          return pageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder> 
           getPageOrBuilderList() {
        if (pageBuilder_ != null) {
          return pageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(page_);
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder addPageBuilder() {
        return getPageFieldBuilder().addBuilder(
            com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.getDefaultInstance());
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder addPageBuilder(
          int index) {
        return getPageFieldBuilder().addBuilder(
            index, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.getDefaultInstance());
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Page page = 8;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder> 
           getPageBuilderList() {
        return getPageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder> 
          getPageFieldBuilder() {
        if (pageBuilder_ == null) {
          pageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.Page.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.PageOrBuilder>(
                  page_,
                  ((bitField0_ & 0x00000080) != 0),
                  getParentForChildren(),
                  isClean());
          page_ = null;
        }
        return pageBuilder_;
      }

      private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS> gps_ =
        java.util.Collections.emptyList();
      private void ensureGpsIsMutable() {
        if (!((bitField0_ & 0x00000100) != 0)) {
          gps_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS>(gps_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder> gpsBuilder_;

      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS> getGpsList() {
        if (gpsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gps_);
        } else {
          return gpsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public int getGpsCount() {
        if (gpsBuilder_ == null) {
          return gps_.size();
        } else {
          return gpsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS getGps(int index) {
        if (gpsBuilder_ == null) {
          return gps_.get(index);
        } else {
          return gpsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder setGps(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.set(index, value);
          onChanged();
        } else {
          gpsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder setGps(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.set(index, builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder addGps(com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.add(value);
          onChanged();
        } else {
          gpsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder addGps(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.add(index, value);
          onChanged();
        } else {
          gpsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder addGps(
          com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.add(builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder addGps(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.add(index, builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder addAllGps(
          java.lang.Iterable<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS> values) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gps_);
          onChanged();
        } else {
          gpsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder clearGps() {
        if (gpsBuilder_ == null) {
          gps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          gpsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public Builder removeGps(int index) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.remove(index);
          onChanged();
        } else {
          gpsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder getGpsBuilder(
          int index) {
        return getGpsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder getGpsOrBuilder(
          int index) {
        if (gpsBuilder_ == null) {
          return gps_.get(index);  } else {
          return gpsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder> 
           getGpsOrBuilderList() {
        if (gpsBuilder_ != null) {
          return gpsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gps_);
        }
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder addGpsBuilder() {
        return getGpsFieldBuilder().addBuilder(
            com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.getDefaultInstance());
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder addGpsBuilder(
          int index) {
        return getGpsFieldBuilder().addBuilder(
            index, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.getDefaultInstance());
      }
      /**
       * <pre>
       *  行程gps点数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.GPS gps = 9;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder> 
           getGpsBuilderList() {
        return getGpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder> 
          getGpsFieldBuilder() {
        if (gpsBuilder_ == null) {
          gpsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPS.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.GPSOrBuilder>(
                  gps_,
                  ((bitField0_ & 0x00000100) != 0),
                  getParentForChildren(),
                  isClean());
          gps_ = null;
        }
        return gpsBuilder_;
      }

      private java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt> evt_ =
        java.util.Collections.emptyList();
      private void ensureEvtIsMutable() {
        if (!((bitField0_ & 0x00000200) != 0)) {
          evt_ = new java.util.ArrayList<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt>(evt_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder> evtBuilder_;

      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt> getEvtList() {
        if (evtBuilder_ == null) {
          return java.util.Collections.unmodifiableList(evt_);
        } else {
          return evtBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public int getEvtCount() {
        if (evtBuilder_ == null) {
          return evt_.size();
        } else {
          return evtBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt getEvt(int index) {
        if (evtBuilder_ == null) {
          return evt_.get(index);
        } else {
          return evtBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder setEvt(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt value) {
        if (evtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvtIsMutable();
          evt_.set(index, value);
          onChanged();
        } else {
          evtBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder setEvt(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder builderForValue) {
        if (evtBuilder_ == null) {
          ensureEvtIsMutable();
          evt_.set(index, builderForValue.build());
          onChanged();
        } else {
          evtBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder addEvt(com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt value) {
        if (evtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvtIsMutable();
          evt_.add(value);
          onChanged();
        } else {
          evtBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder addEvt(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt value) {
        if (evtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvtIsMutable();
          evt_.add(index, value);
          onChanged();
        } else {
          evtBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder addEvt(
          com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder builderForValue) {
        if (evtBuilder_ == null) {
          ensureEvtIsMutable();
          evt_.add(builderForValue.build());
          onChanged();
        } else {
          evtBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder addEvt(
          int index, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder builderForValue) {
        if (evtBuilder_ == null) {
          ensureEvtIsMutable();
          evt_.add(index, builderForValue.build());
          onChanged();
        } else {
          evtBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder addAllEvt(
          java.lang.Iterable<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt> values) {
        if (evtBuilder_ == null) {
          ensureEvtIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, evt_);
          onChanged();
        } else {
          evtBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder clearEvt() {
        if (evtBuilder_ == null) {
          evt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          evtBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public Builder removeEvt(int index) {
        if (evtBuilder_ == null) {
          ensureEvtIsMutable();
          evt_.remove(index);
          onChanged();
        } else {
          evtBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder getEvtBuilder(
          int index) {
        return getEvtFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder getEvtOrBuilder(
          int index) {
        if (evtBuilder_ == null) {
          return evt_.get(index);  } else {
          return evtBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public java.util.List<? extends com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder> 
           getEvtOrBuilderList() {
        if (evtBuilder_ != null) {
          return evtBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(evt_);
        }
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder addEvtBuilder() {
        return getEvtFieldBuilder().addBuilder(
            com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.getDefaultInstance());
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder addEvtBuilder(
          int index) {
        return getEvtFieldBuilder().addBuilder(
            index, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.getDefaultInstance());
      }
      /**
       * <pre>
       *引入页面的数组
       * </pre>
       *
       * <code>repeated .com.autoai.wedata.kittx.uds.log.bean.pbv1.Evt evt = 10;</code>
       */
      public java.util.List<com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder> 
           getEvtBuilderList() {
        return getEvtFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder> 
          getEvtFieldBuilder() {
        if (evtBuilder_ == null) {
          evtBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.Evt.Builder, com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.EvtOrBuilder>(
                  evt_,
                  ((bitField0_ & 0x00000200) != 0),
                  getParentForChildren(),
                  isClean());
          evt_ = null;
        }
        return evtBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.autoai.wedata.kittx.uds.log.bean.pbv1.Track)
    }

    // @@protoc_insertion_point(class_scope:com.autoai.wedata.kittx.uds.log.bean.pbv1.Track)
    private static final com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track();
    }

    public static com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Track>
        PARSER = new com.google.protobuf.AbstractParser<Track>() {
      public Track parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Track(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Track> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Track> getParserForType() {
      return PARSER;
    }

    public com.autoai.wedata.kittx.uds.log.bean.pbv1.TrackBean.Track getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013track.proto\022)com.autoai.wedata.kittx.u" +
      "ds.log.bean.pbv1\032\npage.proto\032\tevt.proto\032" +
      "\tgps.proto\"\312\002\n\005Track\022\022\n\nsession_id\030\001 \001(\t" +
      "\022\024\n\014app_start_ts\030\002 \001(\t\022\023\n\013app_stop_ts\030\003 " +
      "\001(\t\022\020\n\010is_first\030\004 \001(\t\022\021\n\tis_update\030\005 \001(\t" +
      "\022\021\n\tfirst_day\030\006 \001(\t\022\021\n\tfirst_use\030\007 \001(\t\022=" +
      "\n\004page\030\010 \003(\0132/.com.autoai.wedata.kittx.u" +
      "ds.log.bean.pbv1.Page\022;\n\003gps\030\t \003(\0132..com" +
      ".autoai.wedata.kittx.uds.log.bean.pbv1.G" +
      "PS\022;\n\003evt\030\n \003(\0132..com.autoai.wedata.kitt" +
      "x.uds.log.bean.pbv1.EvtB\013B\tTrackBeanb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.getDescriptor(),
          com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.getDescriptor(),
          com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.getDescriptor(),
        }, assigner);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_autoai_wedata_kittx_uds_log_bean_pbv1_Track_descriptor,
        new java.lang.String[] { "SessionId", "AppStartTs", "AppStopTs", "IsFirst", "IsUpdate", "FirstDay", "FirstUse", "Page", "Gps", "Evt", });
    com.autoai.wedata.kittx.uds.log.bean.pbv1.PageBean.getDescriptor();
    com.autoai.wedata.kittx.uds.log.bean.pbv1.EvtBean.getDescriptor();
    com.autoai.wedata.kittx.uds.log.bean.pbv1.GPSBean.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
